{% set name = "rubicon-objc" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-objc-{{ version }}.tar.gz
  sha256: be937d864bd1229f860defabb89b40c53634eedc36448d89ad3c14eb3286e509

build:
  noarch: python
  script:
    # burn in the version so that pip can list it correctly
    - sed -i.bak "3i version = {{ version }}" setup.cfg
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=46.4.0
    - wheel >=0.32.0
  run:
    - python >=3.5

test:
  imports:
    - rubicon
  commands:
    - pip check
    - pip list | grep rubicon-objc.*{{ version }}
  requires:
    - pip

about:
  home: https://beeware.org/rubicon
  summary: A bridge between an Objective C runtime environment and Python.
  dev_url: https://github.com/beeware/rubicon-objc
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
