{% set name = "rubicon-objc" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3d77a5b2d10cb1e49679aa90b7824b46f67b3fd636229aa4a1b902d24aec6a58

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools ==69.5.1
    - setuptools-scm ==8.0.4
  run:
    - python >={{ python_min }}

test:
  imports:
    - rubicon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beeware.org/rubicon
  summary: A bridge between an Objective C runtime environment and Python.
  dev_url: https://github.com/beeware/rubicon-objc
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
