schema_version: 1

context:
  name: rubicon-objc
  version: "0.5.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 1180593935f6a8a39c23b5f4b7baa24aedf9f7285e80804a1d9d6b50a50572f5

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools ==80.9.0
    - setuptools-scm ==8.3.1
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - rubicon
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A bridge between an Objective C runtime environment and Python.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://beeware.org/rubicon
  repository: https://github.com/beeware/rubicon-objc

extra:
  recipe-maintainers:
    - thewchan
